include		$(SRC)/Makefile.master

#
# Default paths or names
#
LIBS =
DYNLIB =	$(LIBRARY:.a=.so$(VERS))
LIBLINK =	$(LIBRARY:.a=.so)
LIBNAME =	$(LIBRARY:lib%.a=%)
LIBLINKPATH =

ROOTINC =	$(ROOT)/include
ROOTLIB =	$(ROOT)/lib
ROOTMAN3 =	$(ROOT)/man/man3

ROOTLIBS =	$(LIBS:%=$(ROOTLIB)/%)
ROOTLINKS =	$(ROOTLIB)/$(LIBLINK)

#
# Link flags
#
ARFLAGS =	r
DYNFLAGS =	-Wl,-h$(DYNLIB) -Wl,-zdefs -fpic
LDLIBS =

SRCS =		$(OBJECTS:%.o=%.c)
OBJS =		$(OBJECTS:%=objs/%)
PICS =		$(OBJECTS:%=pics/%)
DEPS =		$(OBJS:%.o=%.d) $(PICS:%.o=%.d)

# Default build of an archive and a shared object
BUILD.ar =	$(AR) $(ARFLAGS) $@ $(OBJS)
BUILD.so =	$(CC) -o $@ -shared $(DYNFLAGS) $(PICS) $(LDLIBS)

# Default dynamic library symlink
INS.liblink =	$(SYMLINK) $(LIBLINKPATH)$(LIBLINK)$(VERS) $@

# Conditional assignments
$(PICS):	CFLAGS += -fpic -fvisibility=hidden
$(LIBRARY):	DIR = objs
$(DYNLIB):	DIR = pics

#
# Compilation rules
#
objs/%.o pics/%.o: %.c
	$(COMPILE.c) -o $@ $<
	$(POST_PROCESS.o)

.PRECIOUS:	$(LIBS)
