#!/usr/bin/lua

require "wslog.util"

lang = getlang()
params = getparams()

print("Content-type: text/html; charset=utf-8\n")

print("<html>")
print("<head>")
print("<meta charset='utf-8'>")
print("</head>")

print("<body>")

view = params.view or "current"

if view == "summary" then
	require "wslog.summary"
	display()
else
	require "wslog.current"
	display()
end

print("</body>")
print("</html>")

