.Dd May 31, 2018
.Dt WSLOGD.CONF 1
.Os
.Sh NAME
.Nm wslogd
.Nd weather station logger configuration
.Sh DESCRIPTION
The 
.Xr wslogd 1
configuration file.
.Sh OPTIONS
.Bl -tag -width Ds
.It Cm log_facility
The syslog facility. Valid facility names are:
.Cm user
(the default),
.Cm local0
to
.Cm local7
.It Cm log_level
Restrict logging to the specified level. Valid levels are: 'err', 'warning',
or 'notice', 'info' and 'debug'. Default: notice.
.El
.Sh STATION OPTIONS
.Bl -tag -width Ds
.It Cm station.driver (string)
The console driver. Shall be one of: 'vantage', 'ws23xx', 'virt'.
.El
.Sh VANTAGE DRIVER OPTIONS
.Bl -tag -width Ds
.It Cm driver.vantage.tty (string)
The serial console device. Default:
.Pa /dev/ttyUSB0 .
.It Cm driver.vantage.bauds (int)
The serial bauds rate. Valid values are 1200, 2400, 4800, 9600, 14400,
and 19200. The value shall match the console setup value. Default: 19200.
.El
.Sh WS23XX DRIVER OPTIONS
.Bl -tag -width Ds
.It Cm driver.ws23xx.tty (string)
The serial console device. Default:
.Pa /dev/ttyUSB0 .
.El
.Sh VIRTUAL DRIVER OPTIONS
The virual console should be used for testing purpose only.
.Bl -tag -width Ds
.It Cm driver.virt.hw_archive (int)
Turn on hardware archive. Default: 1.
.It Cm driver.virt.io_delay (int)
Virtual I/O delay, in milliseconds. Default: 100.
.El
.Sh ARCHIVE OPTIONS
.Bl -tag -width Ds
.It Cm archive.freq (int)
Archive frequency, in seconds. Default: 0.
.Pp
When the value is set to zero, the *wslogd* daemon probes the device to get
the hardware archive interval, when supported. 1800 is used otherwise.
.It Cm archive.delay (int)
Delay, in seconds, before fetching new data from the device. Default: 15.
.Pp
That delay allows the console to internally build and write archive data. For
example, if archive interval is 30 minutes and the delay is 15 seconds, then
console data will be requested at 00:00:15, 00:30:15, etc. 
.It Cm archive.sqlite.enabled (int)
Enable SQLite database backend. Default: 1.
.It Cm archive.sqlite.db (string)
Path to the SQLite database. Default:
.Pa /var/lib/wslog/wslogd.db .
.Pp
Note that
.Xr wslogd 1
will create the database if the specified file does not
exist. It is not recommended to create the file by yourself.
.El
.Sh WEATHER UNDERGROUND SERVICE OPTIONS
.Bl -tag -width Ds
.It Cm wunder.enabled (int)
Enable report to Weather Underground. Default: 0.
.It Cm wunder.https (int)
Use HTTPS to report data. Default: 1.
.Pp
Unless you have good reasons to do so, it is not recommended to turn of HTTPS,
as
.Xr wslogd 1
would send your password in clear.
.It Cm wunder.station (string)
The Weather Underground station id (mandatory).
.It Cm wunder.password (string)
The Weather Underground password (mandatory).
.It Cm wunder.freq (int)
Default: 300
.El
.Sh SEE ALSO
.Xr wslogd 1
.Sh WSLOG
Part of the
.Xr wslog 1
suite.
